#!/bin/bash
#
# rsyslog-chroot        Startup script
#
# chkconfig: - 75 15
# description: rsyslog wrapper
# processname: rsyslog-chroot
# config: /var/rsyslog-chroot/etc/sysconfig/rsyslog-chroot
# pidfile: /var/rsyslog-chroot/var/run/rsyslog-chroot/rsyslog-chroot.pid
#
### BEGIN INIT INFO
# Provides: rsyslog-chroot
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start:
# Default-Stop:
# Short-Description: start and stop
# Description: 
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions
. /etc/rc.d/init.d/chroot-functions

if [ -f /etc/sysconfig/smorg-chroot ]; then
        . /etc/sysconfig/smorg-chroot
else
    echo "Please set CHROOT_ROOT in /etc/sysconfig/smorg-chroot."
    echo "Aborting."
    exit 1
fi

if [ -f /etc/sysconfig/rsyslog-chroot ]; then
        . /etc/sysconfig/rsyslog-chroot
fi

prog=rsyslog

RETVAL=0

start() {
        chroot $CHROOT_ROOT/ service $prog start
        RETVAL=$?
        return $RETVAL
}

stop() {
        chroot $CHROOT_ROOT/ service $prog stop
}

# See how we were called.
case "$1" in
  start)
        check_chroot
	start
	;;
  stop)
        check_chroot
	stop
	;;
  status)
        check_chroot
        chroot $CHROOT_ROOT/ service $prog status
	RETVAL=$?
	;;
  restart|reload)
        check_chroot
	stop
	start
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|reload|status|help}"
	RETVAL=3
esac

exit $RETVAL

